namespace: claif-dev

# Keycloak-DB configurations
keycloakDb:
  usePersistentStorage: false  # Set to true to use PV/PVC, false to use emptyDir
  replicaCount: 1
  image:
    repository: "docker.io/bitnami/postgresql"
    tag: "12.20.0"
  secretName: "keycloak-db-secrets"
  mountPath: "/bitnami/postgresql"
  nodeAffinity:
    key: "storage-type"
    operator: "In"
    values:
      - "disk"
  persistentVolume:
    type: hostPath
    path: /tmp/keycloak-db
    capacity: 1Gi
    accessMode: ReadWriteOnce
    reclaimPolicy: Retain
    storageClassName: local-storage
    volumeMode: Filesystem
    nodeAffinity: {}
    labels:
      app: keycloak-db
  persistentVolumeClaim:
    storageClassName: local-storage
    accessMode: ReadWriteOnce
    storage: 1Gi
    labels:
      app: keycloak-db

service:
  type: NodePort
  port: 5432
  targetPort: 5432
  nodePort: 30086
