apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/clusters/local/dev/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  dependsOn:
    - name: registry
