apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/local/dev/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
