namespace: claif-dev
replicaCount: 1
secretName: "claif-api-secrets"
containerPort: 8000
command: "./scripts/wait_for_db.sh claif-api-db:5432 && ./scripts/wait_for_keycloak.sh keycloak && ./scripts/seed_db.sh claif-api-db"

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30082
