apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: adminer
  ports:
    - name: adminer-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
