apiVersion: v1
kind: PersistentVolume
metadata:
  name: claif-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/claif-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-type
              operator: In
              values:
                - disk
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/keycloak-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-type
              operator: In
              values:
                - disk
  volumeMode: Filesystem
