apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claif-db-data
  namespace: claif-dev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-data
  namespace: claif-dev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
