apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
      nodePort: 30080
  type: NodePort
