version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    image: traefik:3.1.4
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
    ports:
      - 8080:80    # Traefik's web entrypoint
      - 8081:8080  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./log/traefik:/var/log/traefik"

  claif-api:
    container_name: claif-api
    build:
      context: ./src/claif-api
    command: >
      bash -c "./scripts/wait_for_db.sh claif-db:5432
      && ./scripts/wait_for_keycloak.sh keycloak
      && ./scripts/seed_db.sh claif-db"
    environment:
      - UVICORN_WORKERS=2
      - APP_MODULE=main:app
      - DATABASE_URL=postgresql://claif_db_user:claif_db_password@claif-db:5432/claif_db
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=fastapi
      - KEYCLOAK_CLIENT_ID=fastapi-client
      - KEYCLOAK_CLIENT_SECRET=g07L@Qg#mL&u8ukA2XE@L1wi&hioNRAoRGpYy
      - OPENAPI_KEYCLOAK_SERVER_URL=http://localhost:8085
      - CLAIF_API_HOST=api-gateway
      - CLAIF_API_PORT=80
      - TEST_USER_USERNAME=testuser
      - TEST_USER_PASSWORD=testpassword
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claif-api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.claif-api.entrypoints=web"
      - "traefik.http.services.claif-api.loadbalancer.server.port=8000"
    ports:
      - 8001:8000
    depends_on:
      - claif-db
      - keycloak

  claif-db:
    container_name: claif-db
    image: docker.io/bitnami/postgresql:12.20.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - claif-db-data:/bitnami/postgresql
      - ./src/claif-db/setup-dev-db.sh:/docker-entrypoint-initdb.d/setup-dev-db.sh
    ports:
      - "5433:5432"
  
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8083:8080

  keycloak-db:
    container_name: keycloak-db
    image: docker.io/bitnami/postgresql:12.20.0
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - keycloak-db-data:/bitnami/postgresql
    ports:
      - 5434:5432

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:25.0.6
    command: >
      /bin/bash -c "/opt/bitnami/scripts/keycloak/run.sh & \
      sleep 30 && \
      /opt/bitnami/keycloak/import-dev-settings.sh && \
      wait"
    ports:
      - "8085:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=bitnami
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_REALM=fastapi
      - KEYCLOAK_USER_USERNAME=testuser
      - KEYCLOAK_USER_PASSWORD=testpassword
      - KEYCLOAK_USER_FIRST_NAME=Test
      - KEYCLOAK_USER_LAST_NAME=User
      - KEYCLOAK_USER_EMAIL=testuser@claif.org
      - KEYCLOAK_CLIENT_ID=fastapi-client
      - KEYCLOAK_CLIENT_SECRET=g07L@Qg#mL&u8ukA2XE@L1wi&hioNRAoRGpYy
    volumes:
      - ./src/keycloak/import-dev-settings.sh:/opt/bitnami/keycloak/import-dev-settings.sh
    depends_on:
      - keycloak-db

volumes:
  claif-db-data:
  keycloak-db-data:
