version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    image: traefik:3.1.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - 8080:80
      - 8081:8080  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  claif-api:
    container_name: claif-api
    build:
      context: ./src/claif-api
    command: ["bash", "-c", "./wait-for-db-availability.sh claif-db:5432 && uvicorn main:app --host 0.0.0.0 --port 8000"]

    environment:
      - UVICORN_WORKERS=2
      - APP_MODULE=main:app
      - DATABASE_URL=postgresql://claif_db_user:claif_db_password@claif-db:5432/claif_db
    labels:
      - "traefik.http.routers.app.rule=Host(`127.0.0.1`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    depends_on:
      - claif-db
    ports:
      - 8082:8000

  claif-db:
    container_name: claif-db
    image: docker.io/bitnami/postgresql:12.20.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./src/claif-db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5433:5432"
  
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8083:8080

  keycloak-db:
    container_name: keycloak-db
    image: docker.io/bitnami/postgresql:12.20.0
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak
    ports:
      - 5432:5432

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:25.0.6
    ports:
      - 8085:8080
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=bitnami
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
    depends_on:
      - keycloak-db
