global:
  namespace: claif-staging
  useContainerd: true
  image:
    repository: "docker.io/library"
    tag: "latest"
    pullPolicy: "Never"
  usePersistentStorage: true

keycloak:
  hostname: "keycloak-staging.claif.org"
