global:
  namespace: claif-dev
  useContainerd: false
  image:
    repository: "docker.io/library"
    tag: "latest"
    pullPolicy: "Never"
    usePersistentStorage: false
  keycloakServerUrl: "http://localhost:30085"
