global:
  namespace: claif-staging
  useContainerd: true
  image:
    repository: "docker.io/library"
    tag: "latest"
    pullPolicy: "Never"
  usePersistentStorage: true

keycloak:
  keycloakProduction: true
  service:
    type: NodePort
    port: 8443
    targetPort: 8443
    nodePort: 30085
