global:
  namespace: claif-dev
  useContainerd: false
  image:
    repository: "docker.io/library"
    tag: "latest"
    pullPolicy: "Never"
    usePersistentStorage: false
  keycloakServerUrl: "http://localhost:30085"

claif-api:
  # in dev, this will basically wipe the claif-db and run tests automatically
  command: "./scripts/wait_for_db.sh claif-db:5432 && ./scripts/wait_for_keycloak.sh keycloak && ./scripts/seed_db.sh claif-db \
  && ./scripts/wait_for_minio.sh minio:9000"