apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: copy-keycloak-scripts
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /bin/bash
            - -c
            - |
              cp /opt/bitnami/keycloak/import-dev-settings.sh /tmp/import-dev-settings.sh && chmod +x /tmp/import-dev-settings.sh;
              cp /opt/bitnami/keycloak/create-keycloak-user.sh /tmp/create-keycloak-user.sh && chmod +x /tmp/create-keycloak-user.sh;
              cp /opt/bitnami/keycloak/delete-keycloak-user.sh /tmp/delete-keycloak-user.sh && chmod +x /tmp/delete-keycloak-user.sh;
          volumeMounts:
            - name: keycloak-settings
              mountPath: /opt/bitnami/keycloak/import-dev-settings.sh
              subPath: import-dev-settings.sh
            - name: keycloak-settings
              mountPath: /opt/bitnami/keycloak/create-keycloak-user.sh
              subPath: create-keycloak-user.sh
            - name: keycloak-settings
              mountPath: /opt/bitnami/keycloak/delete-keycloak-user.sh
              subPath: delete-keycloak-user.sh
            - name: tmp-script
              mountPath: /tmp
      containers:
        - name: keycloak
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - /bin/bash
            - -c
            - "/opt/bitnami/scripts/keycloak/run.sh & sleep 30 && /tmp/import-dev-settings.sh && wait"
          env:
            - name: KEYCLOAK_PRODUCTION
              value: {{ .Values.keycloakProduction | quote }}
            {{- if .Values.keycloakProduction }}
            - name: KEYCLOAK_ENABLE_HTTPS
              value: "true"
            - name: KEYCLOAK_HTTPS_USE_PEM
              value: "true"
            - name: KEYCLOAK_HTTPS_CERTIFICATE_FILE
              value: "/opt/bitnami/keycloak/certs/tls.crt"
            - name: KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE
              value: "/opt/bitnami/keycloak/certs/tls.key"
            {{- end }}
            - name: KEYCLOAK_LOG_LEVEL
              value: DEBUG
            - name: KEYCLOAK_DATABASE_VENDOR
              value: postgresql
            - name: KEYCLOAK_DATABASE_HOST
              value: keycloak-db
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDbSecretName }}
                  key: KEYCLOAK_DB_DATABASE
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDbSecretName }}
                  key: KEYCLOAK_DB_USERNAME
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDbSecretName }}
                  key: KEYCLOAK_DB_PASSWORD
            - name: KEYCLOAK_CREATE_ADMIN_USER
              value: {{ .Values.keycloak.createAdminUser | quote }}
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_USER_USERNAME
            - name: KEYCLOAK_USER_FIRST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_USER_FIRST_NAME
            - name: KEYCLOAK_USER_LAST_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_USER_LAST_NAME
            - name: KEYCLOAK_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_USER_EMAIL
            - name: KEYCLOAK_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_USER_PASSWORD
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: KEYCLOAK_CLIENT_SECRET
          volumeMounts:
            - name: tmp-script
              mountPath: /tmp
            {{- if .Values.keycloakProduction }}
            - name: keycloak-tls
              mountPath: /opt/bitnami/keycloak/certs
              readOnly: true
            {{- end }}
      volumes:
        - name: keycloak-settings
          configMap:
            name: keycloak-config
        - name: tmp-script
          emptyDir: {}
        {{- if .Values.keycloakProduction }}
        - name: keycloak-tls
          secret:
            secretName: keycloak-tls-secret
        {{- end }}
