apiVersion: apps/v1
kind: Deployment
metadata:
  name: claif-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: claif-api
  template:
    metadata:
      labels:
        app: claif-api
    spec:
      containers:
      - name: claif-api
        {{- if .Values.useContainerd }}
        image: {{ .Values.image.repository }}/claif-api:{{ .Values.global.image.tag }}
        {{- else }}
        image: claif-api-claif-api:{{ .Values.global.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command: ["/bin/bash", "-c", "{{ .Values.command }}"]
        env:
          - name: UVICORN_WORKERS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: UVICORN_WORKERS
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: DATABASE_URL
          - name: KEYCLOAK_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_SERVER_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_REALM
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_CLIENT_SECRET
          - name: TEST_USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_USER_USERNAME
          - name: TEST_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloakSecretName }}
                key: KEYCLOAK_USER_PASSWORD
          - name: CLAIF_API_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: CLAIF_API_HOST
          - name: CLAIF_API_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: CLAIF_API_PORT
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.claifDbSecretName }}
                key: NEW_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.claifDbSecretName }}
                key: NEW_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.claifDbSecretName }}
                key: NEW_DB_NAME
        ports:
          - containerPort: {{ .Values.containerPort }}
