apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
data:
  setup-dev-db.sh: |
    #!/bin/bash
    set -e

    # Export the password so psql can use it without prompting
    export PGPASSWORD=$POSTGRESQL_PASSWORD

    psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USERNAME" --dbname "$POSTGRESQL_DATABASE" <<-EOSQL
        CREATE USER {{ .Values.dbUser }} WITH PASSWORD '{{ .Values.dbPassword }}';
        CREATE DATABASE {{ .Values.dbName }};
        GRANT ALL PRIVILEGES ON DATABASE {{ .Values.dbName }} TO {{ .Values.dbUser }};
    EOSQL

    # Unset the password after it's used for security reasons
    unset PGPASSWORD
