apiVersion: apps/v1
kind: Deployment
metadata:
  name: claif-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: claif-db
  template:
    metadata:
      labels:
        app: claif-db
    spec:
      containers:
      - name: claif-db
        {{- if .Values.useContainerd }}
        image: {{ .Values.image.repository }}/claif-db:{{ .Values.global.image.tag }}
        {{- else }}
        image: claif-api-claif-db:{{ .Values.global.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: CLAIF_DB_USER
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: CLAIF_DB_PASSWORD
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: CLAIF_DB_DATABASE
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: NEW_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: NEW_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: NEW_DB_NAME
        volumeMounts:
          - name: data
            mountPath: {{ .Values.mountPath }}
      volumes:
        - name: data
          {{- if .Values.usePersistentStorage }}
          persistentVolumeClaim:
            claimName: claif-db-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: db-config
          configMap:
            name: db-config
            defaultMode: 0755
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinity.key }}
                    operator: {{ .Values.nodeAffinity.operator }}
                    values: {{ toYaml .Values.nodeAffinity.values | nindent 22 }}
