apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-claif-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-claif-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-claif-db
    spec:
      containers:
      - name: claif-db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_USERNAME
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_PASSWORD
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_DATABASE
        volumeMounts:
          - name: {{ .Release.Name }}-claif-db-pv
            mountPath: {{ .Values.mountPath }}
      volumes:
      - name: {{ .Release.Name }}-claif-db-pv
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-claif-db-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinity.key }}
                    operator: {{ .Values.nodeAffinity.operator }}
                    values: {{ toYaml .Values.nodeAffinity.values | nindent 22 }}
