apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
spec:
  interval: 5m
  path: "./k8s/clusters/local/dev/namespaces"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
