apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.global.namespace }}
  labels:
    app: minio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.image }}
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: data
          {{- if .Values.global.usePersistentStorage }}
          persistentVolumeClaim:
            claimName: minio-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}