apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-claif-api-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-claif-api-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-claif-api-db
    spec:
      containers:
      - name: claif-api-db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_USERNAME
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_PASSWORD
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: POSTGRESQL_DATABASE
        volumeMounts:
            - name: data
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: data
          {{- if .Values.usePersistentStorage }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-claif-api-db-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeAffinity.key }}
                    operator: {{ .Values.nodeAffinity.operator }}
                    values: {{ toYaml .Values.nodeAffinity.values | nindent 22 }}
