replicaCount: 1

image: "bitnami/minio:2024.10.2"

secretName: "minio-secrets"

service:
  type: NodePort
  ports:
    http: 30086
    dashboard: 30087

mountPath: "/bitnami/minio/data"

nodeAffinity:
  key: "storage-type"
  operator: "In"
  values:
    - "disk"

persistentVolume:
  type: hostPath
  path: /tmp/minio
  capacity: 1Gi
  accessMode: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  nodeAffinity: {}
  labels:
    app: minio

persistentVolumeClaim:
  storageClassName: local-storage
  accessMode: ReadWriteOnce
  storage: 1Gi
  labels:
    app: minio