replicaCount: 1

keycloakProduction: false

image:
  repository: "docker.io/bitnami/keycloak"
  tag: "26.0.5"

secretName: "keycloak-secrets"
keycloakDbSecretName: "keycloak-db-secrets"

keycloak:
  createAdminUser: "true"

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30085
