namespace: claif-dev
replicaCount: 1

image:
  repository: "docker.io/bitnami/keycloak"
  tag: "25.0.6"

secretName: "keycloak-secrets"

keycloak:
  createAdminUser: "true"

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30085
