namespace: claif-dev
replicaCount: 1

secretName: "claif-db-secrets"
mountPath: "/bitnami/postgresql"

nodeAffinity:
  key: "storage-type"
  operator: "In"
  values:
    - "disk"

usePersistentStorage: false

persistentVolume:
  type: hostPath
  path: /tmp/claif-db
  capacity: 1Gi
  accessMode: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  nodeAffinity: {}
  labels:
    app: claif-db

persistentVolumeClaim:
  storageClassName: local-storage
  accessMode: ReadWriteOnce
  storage: 1Gi
  labels:
    app: claif-db

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432
