apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.keycloakDb.replicaCount }}
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: {{ .Values.keycloakDb.image.repository }}:{{ .Values.keycloakDb.image.tag }}
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDb.secretName }}
                  key: KEYCLOAK_DB_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDb.secretName }}
                  key: KEYCLOAK_DB_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloakDb.secretName }}
                  key: KEYCLOAK_DB_DATABASE
          volumeMounts:
            - name: data
              mountPath: {{ .Values.keycloakDb.mountPath }}
      volumes:
        - name: data
          {{- if .Values.global.usePersistentStorage }}
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if .Values.global.usePersistentStorage }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.keycloakDb.nodeAffinity.key }}
                    operator: {{ .Values.keycloakDb.nodeAffinity.operator }}
                    values:
                      {{ toYaml .Values.keycloakDb.nodeAffinity.values | nindent 22 }}
      {{- end }}
