{{- if .Values.global.usePersistentStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.keycloakDb.persistentVolumeClaim.storageClassName }}
  accessModes:
    - {{ .Values.keycloakDb.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.keycloakDb.persistentVolumeClaim.storage }}
  selector:
    matchLabels:
      pv-name: keycloak-db-pv
{{- end }}
